Here I will take the stocks chosen from the reduced daily dataset, and obtain hourly data.

In [11]:
import pandas as pd

In [13]:
df_reduced_daily_stocks = pd.read_csv('transformed_daily_data/dailydata_5years_30ktransacs.csv')
df_reduced_daily_stocks

,timestamp,ticker,open,high,low,close,volume,vwap,transactions
0,2021-05-05,AA,39.37,40.880,38.640,40.60,7.773673e+06,40.1427,54715.0
1,2021-05-06,AA,40.89,41.440,39.280,39.89,7.308031e+06,40.0879,52580.0
2,2021-05-07,AA,39.76,41.380,39.250,41.20,4.909460e+06,40.6481,40057.0
3,2021-05-10,AA,42.75,44.420,41.020,41.04,1.183422e+07,42.5571,81210.0
4,2021-05-11,AA,39.07,42.150,38.960,41.32,9.246082e+06,40.8798,71792.0
...,...,...,...,...,...,...,...,...,...
497833,2026-04-27,ZTS,116.62,119.680,116.600,117.87,3.160355e+06,118.2275,43149.0
497834,2026-04-28,ZTS,117.23,118.290,116.075,116.65,2.972547e+06,117.0538,47388.0
497835,2026-04-29,ZTS,115.50,115.905,112.970,113.83,3.401808e+06,113.9745,47839.0
497836,2026-04-30,ZTS,114.04,115.535,113.790,114.97,4.297206e+06,114.7143,57409.0
497837,2026-05-01,ZTS,116.22,116.250,113.760,114.16,3.203961e+06,114.5220,47928.0

In [5]:
stocks_to_fetch = df_reduced_daily_stocks['ticker'].unique().tolist()

In [6]:
stocks_to_fetch

['AA',
 'AAL',
 'AAPL',
 'ABBV',
 'ABNB',
 'ABT',
 'ACN',
 'ADBE',
 'ADI',
 'ADM',
 'ADP',
 'ADSK',
 'AEM',
 'AEO',
 'AEP',
 'AES',
 'AFL',
 'AFRM',
 'AG',
 'AGNC',
 'AI',
 'AIG',
 'ALB',
 'ALLY',
 'AMAT',
 'AMC',
 'AMCR',
 'AMD',
 'AMGN',
 'AMT',
 'AMZN',
 'ANET',
 'APA',
 'APH',
 'APO',
 'APP',
 'APTV',
 'AR',
 'ARRY',
 'ASAN',
 'ASTS',
 'AVGO',
 'AVTR',
 'AXP',
 'AZN',
 'BA',
 'BAC',
 'BAX',
 'BBY',
 'BE',
 'BEN',
 'BILL',
 'BK',
 'BKR',
 'BLDR',
 'BMY',
 'BRK.B',
 'BSX',
 'BTU',
 'BX',
 'BYND',
 'C',
 'CAG',
 'CAH',
 'CARR',
 'CAT',
 'CB',
 'CCI',
 'CCJ',
 'CCL',
 'CDE',
 'CDNS',
 'CELH',
 'CF',
 'CFG',
 'CHPT',
 'CHTR',
 'CHWY',
 'CI',
 'CL',
 'CLF',
 'CLOV',
 'CMCSA',
 'CME',
 'CMG',
 'CNC',
 'CNP',
 'CNQ',
 'COF',
 'COIN',
 'COP',
 'COST',
 'CPB',
 'CPNG',
 'CPRT',
 'CRH',
 'CRM',
 'CRWD',
 'CSCO',
 'CSGP',
 'CSX',
 'CTSH',
 'CTVA',
 'CVE',
 'CVNA',
 'CVS',
 'CVX',
 'CZR',
 'D',
 'DAL',
 'DASH',
 'DBX',
 'DD',
 'DDOG',
 'DE',
 'DELL',
 'DG',
 'DHI',
 'DHR',
 'DIS',
 'DKNG',
 'DLTR',
 'DOCU',
 'DOW',
 'DT',
 'DUK',
 'DVN',
 'DXCM',
 'EA',
 'EBAY',
 'EL',
 'ELAN',
 'EMR',
 'ENPH',
 'EOG',
 'EOSE',
 'EQT',
 'ET',
 'ETN',
 'ETSY',
 'EW',
 'EXC',
 'EXPE',
 'F',
 'FANG',
 'FAST',
 'FCEL',
 'FCX',
 'FDX',
 'FE',
 'FHN',
 'FIS',
 'FITB',
 'FLEX',
 'FOXA',
 'FSLR',
 'FSLY',
 'FTI',
 'FTNT',
 'FUBO',
 'GE',
 'GILD',
 'GIS',
 'GLW',
 'GM',
 'GME',
 'GOOG',
 'GOOGL',
 'GPN',
 'GS',
 'GT',
 'HAL',
 'HBAN',
 'HD',
 'HIMS',
 'HL',
 'HLT',
 'HON',
 'HPE',
 'HPQ',
 'HST',
 'HUM',
 'HWM',
 'IBM',
 'ICE',
 'ILMN',
 'INTC',
 'INTU',
 'INVH',
 'IOVA',
 'IP',
 'IR',
 'ISRG',
 'IVZ',
 'JBLU',
 'JCI',
 'JNJ',
 'JPM',
 'KDP',
 'KEY',
 'KGC',
 'KHC',
 'KKR',
 'KLAC',
 'KMB',
 'KMI',
 'KMX',
 'KO',
 'KR',
 'KSS',
 'LEN',
 'LIN',
 'LITE',
 'LLY',
 'LMT',
 'LNG',
 'LOW',
 'LRCX',
 'LULU',
 'LUMN',
 'LUV',
 'LVS',
 'LYB',
 'LYFT',
 'LYV',
 'M',
 'MA',
 'MAR',
 'MARA',
 'MCD',
 'MCHP',
 'MDB',
 'MDLZ',
 'MDT',
 'MET',
 'META',
 'MGM',
 'MMM',
 'MNST',
 'MO',
 'MOS',
 'MP',
 'MPC',
 'MRK',
 'MRNA',
 'MRVL',
 'MS',
 'MSFT',
 'MSTR',
 'MTCH',
 'MU',
 'NCLH',
 'NDAQ',
 'NEE',
 'NEM',
 'NET',
 'NFLX',
 'NI',
 'NKE',
 'NLY',
 'NOV',
 'NOW',
 'NRG',
 'NUE',
 'NVAX',
 'NVDA',
 'NXPI',
 'O',
 'OKE',
 'OKTA',
 'OMC',
 'ON',
 'ONDS',
 'OPEN',
 'ORCL',
 'OSCR',
 'OVV',
 'OXY',
 'PAAS',
 'PANW',
 'PATH',
 'PAYX',
 'PBF',
 'PCAR',
 'PCG',
 'PEG',
 'PENN',
 'PEP',
 'PFE',
 'PG',
 'PGR',
 'PHM',
 'PINS',
 'PLD',
 'PLTR',
 'PLUG',
 'PM',
 'PNC',
 'PPL',
 'PSX',
 'PTEN',
 'PTON',
 'PYPL',
 'QCOM',
 'QS',
 'RBLX',
 'RCL',
 'RF',
 'RIG',
 'RIOT',
 'RKT',
 'ROKU',
 'ROST',
 'RRC',
 'RTX',
 'RUN',
 'RXRX',
 'SBUX',
 'SCHW',
 'SEDG',
 'SHOP',
 'SHW',
 'SIRI',
 'SLB',
 'SMCI',
 'SNAP',
 'SNOW',
 'SNPS',
 'SO',
 'SPCE',
 'SPGI',
 'SPOT',
 'SRE',
 'STM',
 'STNE',
 'STT',
 'STX',
 'SU',
 'SWKS',
 'SYF',
 'SYK',
 'SYY',
 'T',
 'TDOC',
 'TEAM',
 'TECK',
 'TER',
 'TFC',
 'TGT',
 'TJX',
 'TLRY',
 'TMO',
 'TMUS',
 'TPR',
 'TSCO',
 'TSLA',
 'TSN',
 'TTD',
 'TTWO',
 'TWLO',
 'TXN',
 'U',
 'UAA',
 'UAL',
 'UBER',
 'UNH',
 'UNP',
 'UPS',
 'UPST',
 'USB',
 'V',
 'VFC',
 'VICI',
 'VLO',
 'VRT',
 'VRTX',
 'VST',
 'VTRS',
 'VZ',
 'W',
 'WDAY',
 'WDC',
 'WELL',
 'WFC',
 'WM',
 'WMB',
 'WMT',
 'WY',
 'WYNN',
 'XEL',
 'XOM',
 'XP',
 'Z',
 'ZIM',
 'ZM',
 'ZS',
 'ZTS']

In [8]:
df_reduced_daily_stocks['ticker'].nunique()

397

In my smaller version, I set 5000 hours. With 7 trading hours each day that would equate to about 714 days. 

With 30 stocks, that gave me 150000 rows, and that used I believe under 20% of my API credits for the day. (750000 rows with the same columns is the threshold I will plan for).

Now with 397 stocks, I can comfortably get 1889 hours of data. At 7 trading hours a day that's 269 days. 

I'll go with 180 days, which is about 1260 hours, I'll round up to 1270 to ensure no mid-day cutoffs.

In [9]:
import requests
import pandas as pd
from pathlib import Path
import time

def load_api_key(filepath="api_keys/twelvedata.txt"):
    return Path(filepath).read_text(encoding="utf-8").strip()


def get_twelve_data_hourly(ticker, api_key, outputsize=5000):
    url = "https://api.twelvedata.com/time_series"

    params = {
        "symbol": ticker,
        "interval": "1h",
        "outputsize": outputsize,
        "apikey": api_key,
    }

    r = requests.get(url, params=params, timeout=30)
    r.raise_for_status()
    data = r.json()

    if "values" not in data:
        raise ValueError(f"Twelve Data error for {ticker}: {data}")

    df = pd.DataFrame(data["values"])

    df = df.rename(columns={
        "datetime": "timestamp",
        "open": "open",
        "high": "high",
        "low": "low",
        "close": "close",
        "volume": "volume",
    })

    df["timestamp"] = pd.to_datetime(df["timestamp"])
    df["ticker"] = ticker

    for col in ["open", "high", "low", "close", "volume"]:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    df["vwap"] = pd.NA
    df["transactions"] = pd.NA

    df = df[
        ["timestamp", "ticker", "open", "high", "low", "close", "volume", "vwap", "transactions"]
    ]

    return df.sort_values("timestamp").reset_index(drop=True)


def download_twelve_data_hourly_for_tickers(
    tickers,
    api_key_path="api_keys/twelve_data.txt",
    save_path="raw_hourly_data.csv",
    sleep_seconds=8
):
    api_key = load_api_key(api_key_path)
    all_dfs = []

    for ticker in tickers:
        print(f"Downloading {ticker}...")
        df = get_twelve_data_hourly(ticker, api_key)
        all_dfs.append(df)
        time.sleep(sleep_seconds)

    combined_df = pd.concat(all_dfs, ignore_index=True)
    combined_df = combined_df.sort_values(["ticker", "timestamp"]).reset_index(drop=True)

    Path(save_path).parent.mkdir(parents=True, exist_ok=True)
    combined_df.to_csv(save_path, index=False)

    print(f"Saved {len(combined_df):,} rows to {save_path}")

    return combined_df

In [10]:
# I'll call this list directly from the other dataframe
tickers = df_reduced_daily_stocks['ticker'].unique().tolist()



hourly_df = download_twelve_data_hourly_for_tickers(
    tickers=tickers,
    api_key_path="api_keys/twelvedata.txt",
    save_path="raw_hourly_data.csv",
    sleep_seconds=8
)

hourly_df.head()

Downloading AA...
Downloading AAL...
Downloading AAPL...
Downloading ABBV...
Downloading ABNB...
Downloading ABT...
Downloading ACN...
Downloading ADBE...
Downloading ADI...
Downloading ADM...
Downloading ADP...
Downloading ADSK...
Downloading AEM...
Downloading AEO...
Downloading AEP...
Downloading AES...
Downloading AFL...
Downloading AFRM...
Downloading AG...
Downloading AGNC...
Downloading AI...
Downloading AIG...
Downloading ALB...
Downloading ALLY...
Downloading AMAT...
Downloading AMC...
Downloading AMCR...
Downloading AMD...
Downloading AMGN...
Downloading AMT...
Downloading AMZN...
Downloading ANET...
Downloading APA...
Downloading APH...
Downloading APO...
Downloading APP...
Downloading APTV...
Downloading AR...
Downloading ARRY...
Downloading ASAN...
Downloading ASTS...
Downloading AVGO...
Downloading AVTR...
Downloading AXP...
Downloading AZN...
Downloading BA...
Downloading BAC...
Downloading BAX...
Downloading BBY...
Downloading BE...
Downloading BEN...
Downloading BILL...
Downloading BK...
Downloading BKR...
Downloading BLDR...
Downloading BMY...
Downloading BRK.B...
Downloading BSX...
Downloading BTU...
Downloading BX...
Downloading BYND...
Downloading C...
Downloading CAG...
Downloading CAH...
Downloading CARR...
Downloading CAT...
Downloading CB...
Downloading CCI...
Downloading CCJ...
Downloading CCL...
Downloading CDE...
Downloading CDNS...
Downloading CELH...
Downloading CF...
Downloading CFG...
Downloading CHPT...
Downloading CHTR...
Downloading CHWY...
Downloading CI...
Downloading CL...
Downloading CLF...
Downloading CLOV...
Downloading CMCSA...
Downloading CME...
Downloading CMG...
Downloading CNC...
Downloading CNP...
Downloading CNQ...
Downloading COF...
Downloading COIN...
Downloading COP...
Downloading COST...
Downloading CPB...
Downloading CPNG...
Downloading CPRT...
Downloading CRH...
Downloading CRM...
Downloading CRWD...
Downloading CSCO...
Downloading CSGP...
Downloading CSX...
Downloading CTSH...
Downloading CTVA...
Downloading CVE...
Downloading CVNA...
Downloading CVS...
Downloading CVX...
Downloading CZR...
Downloading D...
Downloading DAL...
Downloading DASH...
Downloading DBX...
Downloading DD...
Downloading DDOG...
Downloading DE...
Downloading DELL...
Downloading DG...
Downloading DHI...
Downloading DHR...
Downloading DIS...
Downloading DKNG...
Downloading DLTR...
Downloading DOCU...
Downloading DOW...
Downloading DT...
Downloading DUK...
Downloading DVN...
Downloading DXCM...
Downloading EA...
Downloading EBAY...
Downloading EL...
Downloading ELAN...
Downloading EMR...
Downloading ENPH...
Downloading EOG...
Downloading EOSE...
Downloading EQT...
Downloading ET...
Downloading ETN...
Downloading ETSY...
Downloading EW...
Downloading EXC...
Downloading EXPE...
Downloading F...
Downloading FANG...
Downloading FAST...
Downloading FCEL...
Downloading FCX...
Downloading FDX...
Downloading FE...
Downloading FHN...
Downloading FIS...
Downloading FITB...
Downloading FLEX...
Downloading FOXA...
Downloading FSLR...
Downloading FSLY...
Downloading FTI...
Downloading FTNT...
Downloading FUBO...
Downloading GE...
Downloading GILD...
Downloading GIS...
Downloading GLW...
Downloading GM...
Downloading GME...
Downloading GOOG...
Downloading GOOGL...
Downloading GPN...
Downloading GS...
Downloading GT...
Downloading HAL...
Downloading HBAN...
Downloading HD...
Downloading HIMS...
Downloading HL...
Downloading HLT...
Downloading HON...
Downloading HPE...
Downloading HPQ...
Downloading HST...
Downloading HUM...
Downloading HWM...
Downloading IBM...
Downloading ICE...
Downloading ILMN...
Downloading INTC...
Downloading INTU...
Downloading INVH...
Downloading IOVA...
Downloading IP...
Downloading IR...
Downloading ISRG...
Downloading IVZ...
Downloading JBLU...
Downloading JCI...
Downloading JNJ...
Downloading JPM...
Downloading KDP...
Downloading KEY...
Downloading KGC...
Downloading KHC...
Downloading KKR...
Downloading KLAC...
Downloading KMB...
Downloading KMI...
Downloading KMX...
Downloading KO...
Downloading KR...
Downloading KSS...
Downloading LEN...
Downloading LIN...
Downloading LITE...
Downloading LLY...
Downloading LMT...
Downloading LNG...
Downloading LOW...
Downloading LRCX...
Downloading LULU...
Downloading LUMN...
Downloading LUV...
Downloading LVS...
Downloading LYB...
Downloading LYFT...
Downloading LYV...
Downloading M...
Downloading MA...
Downloading MAR...
Downloading MARA...
Downloading MCD...
Downloading MCHP...
Downloading MDB...
Downloading MDLZ...
Downloading MDT...
Downloading MET...
Downloading META...
Downloading MGM...
Downloading MMM...
Downloading MNST...
Downloading MO...
Downloading MOS...
Downloading MP...
Downloading MPC...
Downloading MRK...
Downloading MRNA...
Downloading MRVL...
Downloading MS...
Downloading MSFT...
Downloading MSTR...
Downloading MTCH...
Downloading MU...
Downloading NCLH...
Downloading NDAQ...
Downloading NEE...
Downloading NEM...
Downloading NET...
Downloading NFLX...
Downloading NI...
Downloading NKE...
Downloading NLY...
Downloading NOV...
Downloading NOW...
Downloading NRG...
Downloading NUE...
Downloading NVAX...
Downloading NVDA...
Downloading NXPI...
Downloading O...
Downloading OKE...
Downloading OKTA...
Downloading OMC...
Downloading ON...
Downloading ONDS...
Downloading OPEN...
Downloading ORCL...
Downloading OSCR...
Downloading OVV...
Downloading OXY...
Downloading PAAS...
Downloading PANW...
Downloading PATH...
Downloading PAYX...
Downloading PBF...
Downloading PCAR...
Downloading PCG...
Downloading PEG...
Downloading PENN...
Downloading PEP...
Downloading PFE...
Downloading PG...
Downloading PGR...
Downloading PHM...
Downloading PINS...
Downloading PLD...
Downloading PLTR...
Downloading PLUG...
Downloading PM...
Downloading PNC...
Downloading PPL...
Downloading PSX...
Downloading PTEN...
Downloading PTON...
Downloading PYPL...
Downloading QCOM...
Downloading QS...
Downloading RBLX...
Downloading RCL...
Downloading RF...
Downloading RIG...
Downloading RIOT...
Downloading RKT...
Downloading ROKU...
Downloading ROST...
Downloading RRC...
Downloading RTX...
Downloading RUN...
Downloading RXRX...
Downloading SBUX...
Downloading SCHW...
Downloading SEDG...
Downloading SHOP...
Downloading SHW...
Downloading SIRI...
Downloading SLB...
Downloading SMCI...
Downloading SNAP...
Downloading SNOW...
Downloading SNPS...
Downloading SO...
Downloading SPCE...
Downloading SPGI...
Downloading SPOT...
Downloading SRE...
Downloading STM...
Downloading STNE...
Downloading STT...
Downloading STX...
Downloading SU...
Downloading SWKS...
Downloading SYF...
Downloading SYK...
Downloading SYY...
Downloading T...
Downloading TDOC...
Downloading TEAM...
Downloading TECK...
Downloading TER...
Downloading TFC...
Downloading TGT...
Downloading TJX...
Downloading TLRY...
Downloading TMO...
Downloading TMUS...
Downloading TPR...
Downloading TSCO...
Downloading TSLA...
Downloading TSN...
Downloading TTD...
Downloading TTWO...
Downloading TWLO...
Downloading TXN...
Downloading U...
Downloading UAA...
Downloading UAL...
Downloading UBER...
Downloading UNH...
Downloading UNP...
Downloading UPS...
Downloading UPST...
Downloading USB...
Downloading V...
Downloading VFC...
Downloading VICI...
Downloading VLO...
Downloading VRT...
Downloading VRTX...
Downloading VST...
Downloading VTRS...
Downloading VZ...
Downloading W...
Downloading WDAY...
Downloading WDC...
Downloading WELL...
Downloading WFC...
Downloading WM...
Downloading WMB...
Downloading WMT...
Downloading WY...
Downloading WYNN...
Downloading XEL...
Downloading XOM...
Downloading XP...
Downloading Z...
Downloading ZIM...
Downloading ZM...
Downloading ZS...
Downloading ZTS...
Saved 1,985,000 rows to raw_hourly_data.csv

,timestamp,ticker,open,high,low,close,volume,vwap,transactions
0,2023-06-23 15:30:00,AA,32.590000,32.89,32.580000,32.820000,1056860,NaN,NaN
1,2023-06-26 09:30:00,AA,32.780000,33.53,32.780000,33.380000,563671,NaN,NaN
2,2023-06-26 10:30:00,AA,33.390000,33.39,32.990000,33.043499,396548,NaN,NaN
3,2023-06-26 11:30:00,AA,33.060001,33.46,33.000000,33.242900,459899,NaN,NaN
4,2023-06-26 12:30:00,AA,33.259900,33.30,33.099998,33.190000,293175,NaN,NaN

In [14]:
import pandas as pd
df = pd.read_csv('raw_hourly_data/raw_hourly_data_397_stocks.csv')
df

,timestamp,ticker,open,high,low,close,volume,vwap,transactions
0,2023-06-23 15:30:00,AA,32.590000,32.89,32.580000,32.820000,1056860,NaN,NaN
1,2023-06-26 09:30:00,AA,32.780000,33.53,32.780000,33.380000,563671,NaN,NaN
2,2023-06-26 10:30:00,AA,33.390000,33.39,32.990000,33.043499,396548,NaN,NaN
3,2023-06-26 11:30:00,AA,33.060001,33.46,33.000000,33.242900,459899,NaN,NaN
4,2023-06-26 12:30:00,AA,33.259900,33.30,33.099998,33.190000,293175,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1984995,2026-05-04 11:30:00,ZTS,113.040001,113.12,112.185000,112.185000,285011,NaN,NaN
1984996,2026-05-04 12:30:00,ZTS,112.180000,113.19,112.099998,113.080002,259883,NaN,NaN
1984997,2026-05-04 13:30:00,ZTS,113.059998,113.17,112.740000,113.004997,243781,NaN,NaN
1984998,2026-05-04 14:30:00,ZTS,112.985000,113.20,112.320000,112.350000,371968,NaN,NaN
1984999,2026-05-04 15:30:00,ZTS,112.320000,112.97,112.270000,112.710000,835559,NaN,NaN

In [15]:
df['timestamp'].nunique()

6923

In [16]:
df['ticker'].nunique()

397

In [17]:
df['ticker'].value_counts()

ticker
AA      5000
OPEN    5000
ON      5000
OMC     5000
OKTA    5000
        ...
EL      5000
EBAY    5000
EA      5000
DXCM    5000
ZTS     5000
Name: count, Length: 397, dtype: int64

397 stocks with 5000 hours gave me about 2 million rows and used about half of my free API credits for the day.

If I went with 6000 stocks, I'd have to reduce to 333 trading hours (47 trading days) to achieve the same data size. Could maybe double that to 630 trading hours to give me 90 trading days and just get under the wire for API credits.