In [1]:
with open("daily_data/COMMAND EVERYTHING.txt", "r") as file:
    code = file.read()
    exec(code)

df_daily_1_yr
(701568, 19)
df_daily_1_yr_no_null
(698784, 19)
df_daily_2_yr
(1397568, 19)
df_daily_2_yr_no_null
(1394784, 19)
df_daily_5_yr
(3493832, 19)
df_daily_5_yr_no_null
(3215432, 19)

In [3]:
df_daily_5_yr

,timestamp,ticker,open,high,low,close,volume,vwap,transactions,name,market_cap,exchange,country,SMA10,SMA20,SMA50,SMA100,pct_change_from_prev,next_close_pct_change,close_pct_of_day1
0,2021-05-24,A,133.51,134.41,132.5300,133.34,1.325305e+06,133.6936,18683.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us,NaN,NaN,NaN,NaN,NaN,-0.082496,100.000000
1,2021-05-25,A,133.41,134.80,133.0100,133.23,1.905708e+06,133.6992,26967.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us,NaN,NaN,NaN,NaN,-0.082496,0.045035,99.917504
2,2021-05-26,A,136.30,138.00,133.2505,133.29,2.530998e+06,134.5671,31259.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us,NaN,NaN,NaN,NaN,0.045035,3.188536,99.962502
3,2021-05-27,A,133.32,138.14,133.1600,137.54,3.720923e+06,137.2590,37177.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us,NaN,NaN,NaN,NaN,3.188536,0.428966,103.149843
4,2021-05-28,A,138.60,139.21,138.0001,138.13,1.289049e+06,138.4188,20108.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us,NaN,NaN,NaN,NaN,0.428966,-0.673279,103.592320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3493827,2026-05-15,ZYME,24.50,25.34,23.6346,23.93,6.407959e+05,23.8908,11366.0,Zymeworks Inc.,1.827577e+09,XNAS,us,25.195,26.5305,25.6757,24.81475,-0.125209,2.089427,82.975035
3493828,2026-05-18,ZYME,23.93,24.70,23.8800,24.43,7.502414e+05,24.3372,14709.0,Zymeworks Inc.,1.827577e+09,XNAS,us,24.960,26.3595,25.6827,24.78285,2.089427,-0.122800,84.708738
3493829,2026-05-19,ZYME,24.19,24.55,23.8700,24.40,6.153201e+05,24.3494,12503.0,Zymeworks Inc.,1.827577e+09,XNAS,us,24.732,26.1660,25.6857,24.75895,-0.122800,1.803279,84.604716
3493830,2026-05-20,ZYME,24.40,25.20,24.2650,24.84,5.426638e+05,24.8734,13051.0,Zymeworks Inc.,1.827577e+09,XNAS,us,24.455,25.9815,25.6733,24.73875,1.803279,1.086957,86.130374
3493831,2026-05-21,ZYME,24.42,25.36,24.3700,25.11,6.186212e+05,25.0966,11303.0,Zymeworks Inc.,1.827577e+09,XNAS,us,24.306,25.8655,25.6727,24.72115,1.086957,NaN,87.066574

In [2]:
df_daily_5_yr_no_null

,timestamp,ticker,open,high,low,close,volume,vwap,transactions,name,market_cap,exchange,country,SMA10,SMA20,SMA50,SMA100,pct_change_from_prev,next_close_pct_change,close_pct_of_day1
99,2021-10-13,A,149.08,150.88,148.7400,150.22,1.509180e+06,150.0580,22002.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us,152.854,161.1215,165.4324,155.53790,1.534302,1.577686,100.000000
100,2021-10-14,A,151.62,153.48,151.6200,152.59,1.434114e+06,152.4844,21643.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us,152.360,160.0870,165.3988,155.73040,1.577686,0.445639,101.577686
101,2021-10-15,A,153.14,153.89,152.5500,153.27,1.397821e+06,153.2741,17002.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us,152.088,159.0535,165.3634,155.93080,0.445639,0.985190,102.030355
102,2021-10-18,A,153.63,155.42,152.3900,154.78,1.183713e+06,154.7701,18476.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us,152.330,158.2255,165.3450,156.14570,0.985190,0.542706,103.035548
103,2021-10-19,A,155.96,157.46,155.5500,155.62,1.025510e+06,156.2544,16714.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us,152.589,157.4345,165.3266,156.32650,0.542706,1.265904,103.594728
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3493826,2026-05-14,ZYME,24.75,24.75,23.5000,23.96,5.576886e+05,23.9100,10141.0,Zymeworks Inc.,1.827577e+09,XNAS,us,25.463,26.7240,25.6931,24.84775,-2.482702,-0.125209,94.741004
3493827,2026-05-15,ZYME,24.50,25.34,23.6346,23.93,6.407959e+05,23.8908,11366.0,Zymeworks Inc.,1.827577e+09,XNAS,us,25.195,26.5305,25.6757,24.81475,-0.125209,2.089427,94.622380
3493828,2026-05-18,ZYME,23.93,24.70,23.8800,24.43,7.502414e+05,24.3372,14709.0,Zymeworks Inc.,1.827577e+09,XNAS,us,24.960,26.3595,25.6827,24.78285,2.089427,-0.122800,96.599446
3493829,2026-05-19,ZYME,24.19,24.55,23.8700,24.40,6.153201e+05,24.3494,12503.0,Zymeworks Inc.,1.827577e+09,XNAS,us,24.732,26.1660,25.6857,24.75895,-0.122800,1.803279,96.480822
3493830,2026-05-20,ZYME,24.40,25.20,24.2650,24.84,5.426638e+05,24.8734,13051.0,Zymeworks Inc.,1.827577e+09,XNAS,us,24.455,25.9815,25.6733,24.73875,1.803279,1.086957,98.220641